trigger:
  branches:
    include:
      - test_docker

  paths:
    include:
      - frontend/*

variables:
  imageRepository1: 'invent_nginx'
  dockerfilePath1: './Dockerfile.nginx'
  imageRepository2: 'invent_frontend'
  dockerfilePath2: './Dockerfile.frontend'
  containerRegistry: 'uniinventacrdev.azurecr.io'
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'uniinventacrdev'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  kubernetesCluster: 'uni-apps-aks-invent-dev'
  kubernetesServiceConnection: 'INVENT-DEV-uni-apps-aks-invent-dev-invent-dev-1662392151258'
  namespace: 'invent-dev'
  ${{ if endsWith( variables['Build.SourceBranchName'], 'test_docker' ) }}:
    envtag: 'thisisatestag'
  ${{ else }}:
    envtag: 'anothertesttag'



stages:

  - stage: Build_Docker 
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build_Nginx job
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "TAG IS $(envtag)"
            displayName: 'Display tag'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository1)
              dockerfile: $(dockerfilePath1)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
      - job: Build_Frontend
        displayName: Build_Frontend job
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "TAG IS $(envtag)"
            displayName: 'Display tag'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository2)
              dockerfile: $(dockerfilePath2)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest