{{- if not .Values.unitTests.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invent-celery
  labels:
    {{- include "invent-django.labels" . | nindent 4 }}-celery
spec:
  replicas: {{ .Values.replicaCountCelery }}
  selector:
    matchLabels:
      {{- include "invent-django.selectorLabels" . | nindent 6 }}-celery
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "invent-django.selectorLabels" . | nindent 8 }}-celery
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "invent-django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-{{ include "invent-django.fullname" . }}-keyvault
      containers:
        - name: invent-celery
          args:
            - /usr/local/bin/celery
            - -A
            - scheduler
            - worker
            - -B
            - -l
            - info
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: secret-key-{{ .Values.environment }}
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: uni-invent-{{ .Values.environment }}-id
            - name: AZURE_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: uni-invent-{{ .Values.environment }}-secret
            - name: AZURE_TENANT
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: azure-tenant
            - name: OSM_MAP_CLI_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: osm-map-cli-key-{{ .Values.environment }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-{{ include "invent-django.fullname" . }}-keyvault
                  key: {{ .Values.envFullName }}-azure-postgres-password
            - name: "C_FORCE_ROOT"
              value: "true"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
