apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-django
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.vault.clientID }}   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ .Values.vault.name }}        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: osm-map-cli-key
          objectType: secret
        - |
          objectName: secret-key
          objectType: secret
        - |
          objectName: azure-secret
          objectType: secret
        - |
          objectName: azure-client-id
          objectType: secret
        - |
          objectName: azure-tenant
          objectType: secret
        - |
          objectName: {{ .Values.envFullName }}-azure-postgres-password
          objectType: secret
    tenantId: {{ .Values.vault.tenantID }}
  secretObjects:
    - secretName: azure-keyvault-django
      data:
        - key: osm-map-cli-key
          objectName: osm-map-cli-key
        - key: secret-key
          objectName: secret-key
        - key: azure-secret
          objectName: azure-secret
        - key: azure-client-id
          objectName: azure-client-id
        - key: azure-tenant
          objectName: azure-tenant
        - key: {{ .Values.envFullName }}-azure-postgres-password
          objectName: {{ .Values.envFullName }}-azure-postgres-password
      type: Opaque