apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "invent-django.labels" . | nindent 4 }}
  name: {{ include "invent-django.fullname" . }}-translations
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageCLass }}
  resources:
    requests:
      storage: {{ .Values.storage.translationsSize }}