trigger:
  branches:
    include:
      - dev

  paths:
    include:
      - frontend/*
      - nginx/*

pr: none

steps:
- script: echo "This pipeline will trigger the DEV Frontend pipeline in Azure DevOps."