trigger:
  branches:
    include:
      - test_docker

  paths:
    include:
      - frontend/*

pr: none

steps:
- script: echo "This pipeline will trigger the DEV Frontend pipeline in Azure DevOps."