trigger:
  branches:
    include:
      - uat

  paths:
    include:
      - frontend/*
      - nginx/*

pr: none

steps:
- script: echo "This pipeline will trigger the UAT Frontend pipeline in Azure DevOps."